#https://github.com/telefonicaid/fiware-orion/blob/master/docker/README.md
version: "3"

services:
  orion:
    image: telefonicaiot/fiware-orion
    ports:
      - "1026:1026"
    depends_on:
      - mongo
    command: -dbURI mongodb://mongo

  mongo:
    image: mongo:6.0
    command: --nojournal
    ports:
      - "27017:27017"  # Add this line to expose MongoDB port
